# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Disco < Formula
    desc "Utility for bulk image, license, and vulnerability discovery in containerize workloads on GCP."
    homepage "https://github.com/mchmarny/disco"
    version "0.3.5"
    license "Apache-2.0"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/mchmarny/disco/releases/download/v0.3.5/disco_darwin_arm64"
        sha256 "5aaa76c74c337e6d2364ca82e331484697d4865f45666e94bf6d1bf93b16ca41"
  
        def install
          bin.install "disco_darwin_arm64" => "disco"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/mchmarny/disco/releases/download/v0.3.5/disco_darwin_amd64"
        sha256 "c7802acec263c57ba1b9f4ee1e71c830345c1bf41c6d02677c4a888383aadbf1"
  
        def install
          bin.install "disco_darwin_amd64" => "disco"
        end
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/mchmarny/disco/releases/download/v0.3.5/disco_linux_arm64"
        sha256 "52df60108fc554bcfa719ab1cb9550910479d1ef0c333980e2561f4e2a6ddbfc"
  
        def install
          bin.install "disco_linux_arm64" => "disco"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/mchmarny/disco/releases/download/v0.3.5/disco_linux_amd64"
        sha256 "ef6657f7d0f1670b4af83dfdf82281d291bd69360930d1e6ecad7c533d95b67f"
  
        def install
          bin.install "disco_linux_amd64" => "disco"
        end
      end
    end
  end