# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vimp < Formula
  desc "Vulnerability Import CLI"
  homepage "https://github.com/mchmarny/vimp"
  version "0.5.11"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/mchmarny/vimp/releases/download/v0.5.11/vimp_0.5.11_darwin_all"
    sha256 "983fd7b800f153db775df482f57d8356d89af8fdd6c2819b16fa57c048887ac1"

    def install
      bin.install "vimp_0.5.11_darwin_all" => "vimp"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/vimp/releases/download/v0.5.11/vimp_0.5.11_linux_arm64"
      sha256 "199c468fdca592fbeba45fb8faeb0647e2190091f359078b6f1e6d67af22434c"

      def install
        bin.install "vimp_0.5.11_linux_arm64" => "vimp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/vimp/releases/download/v0.5.11/vimp_0.5.11_linux_amd64"
      sha256 "c1f7b56825cff4196a8d1e427f23510f71f6cd40ceacfe52328d72df254d04fe"

      def install
        bin.install "vimp_0.5.11_linux_amd64" => "vimp"
      end
    end
  end

  test do
    system "#{bin}/vimp --version"
  end
end
