# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vulctl < Formula
  desc "Vulnerability management tool."
  homepage "https://github.com/mchmarny/vulctl"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/mchmarny/vulctl/releases/download/v0.3.0/vulctl_0.3.0_darwin_all"
    sha256 "bfc16901a0ee0ce4db81ee95885c91f38b68e1487f583734476a667b41563191"

    def install
      bin.install "vulctl_0.3.0_darwin_all" => "vulctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/vulctl/releases/download/v0.3.0/vulctl_0.3.0_linux_arm64"
      sha256 "0e559075ca9d78972b249c42da457dea3c1e0a97172df6eb40f0503244fa0425"

      def install
        bin.install "vulctl_0.3.0_linux_arm64" => "vulctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/vulctl/releases/download/v0.3.0/vulctl_0.3.0_linux_amd64"
      sha256 "ebde837e04dab017b68c92d9502e3581fe4da26a702c0d0a47bb7ec34809a430"

      def install
        bin.install "vulctl_0.3.0_linux_amd64" => "vulctl"
      end
    end
  end

  test do
    system "#{bin}/vulctl --version"
  end
end
